name: Autofill front matter if absent

on:
    workflow_dispatch:
    workflow_call:
     
permissions:
  contents: write
  pull-requests: write

jobs:
  call_shared_workflow:
    uses: OutSystems/tk-cicd/.github/workflows/autofill-frontmatter.yml@autofill-frontmatter
    with:
      GITHUB_REPOSITORY: ${{ github.repository }}
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ACTION_TYPE: ${{ github.event.action }}  # Pass the action type (opened or synchronize)
      BEFORE_SHA: ${{ github.event.before }}   # Pass the SHA of the commit before the synchronization
      AFTER_SHA: ${{ github.event.after }}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}  # Base branch of the pull request
      HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}  # Head branch of the pull request 
    secrets: inherit
